### ISSUE TITLE
In some chapters it returns null

### ISSUE THREAD

**Issue by Ruthder** [ChrisMichaelPerezSantiago/jkanime#2]
In some chapters of the anime "ACCA: 13-ku Kansatsu-ka" the api returns null, although in jkanime page the links exist.

PD: I have tried with "https://jkanime.chrismichael.now.sh/api/v1/video/acca-13-ku-kansatsu-ka/1/" link, and  I have tried with some more chapters of this anime.

**Comment by ChrisMichaelPerezSantiago** [comment]
Hello @Ruthder ,

Unfortunately right now I am not going to be able to continue to maintain the library as I will start working this week and time will not allow me to do the maintenance.

But yes, I checked and there are some anime that is not showing the data ..

I recommend that as soon as possible you give a fork to the repo and locally maintain it, since I will stop maintaining it as soon as I start working this week.

If you have any questions about the code and how to begin to understand it, you can let me know, and I will help you. So that you can continue to maintain it without problem.

I hope you understand!
